import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type IRootLayoutProps = Readonly<{
  children: React.ReactNode
}>

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="pt-Br">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
